### ISSUE TITLE
Discussions regarding GSoC'20 : Develop FLINT JSON User Interface

### ISSUE THREAD

**Issue by abhi211199** [moja-global/GSoC.FLINT.JSON_Interface#1]
Hi, My name is [Abhishek Garain](https://github.com/abhi211199), moja global's GSoC'20 student, currently working to create an JSON user interface for FLINT.
I will be using this issue to communicate with my mentors regarding weekly and monthly deliverables and progress on my work plans.
My schedule of deliverables can be found [here](https://docs.google.com/document/d/1dZtNWXXPdBDz9AmA5wtka65AybBUs5isruUsA_aRiOs/edit?usp=sharing)
The flowcharts of main features in my project are:
Creation of a file!
![create_file](https://user-images.githubusercontent.com/36303692/81710700-9ab55d00-9490-11ea-8436-f554624b381a.png)
Creation of a CFG file!
![create_CFG](https://user-images.githubusercontent.com/36303692/81710704-9be68a00-9490-11ea-9295-8850d8229295.png)
Opening a file!
![open_file](https://user-images.githubusercontent.com/36303692/81710658-8cffd780-9490-11ea-857d-7fc4448a2a55.png)
I am currently working on wireframes. Once they are ready, I will update this issue.

**Comment by abhi211199** [comment]
@mfellows sir, here are my wireframes for creating  a JSON file and creating a CFG file.
## Wireframe for Creation of JSON file
![wireframe_create_file](https://user-images.githubusercontent.com/36303692/81834923-43ca8900-955f-11ea-8116-b95e5cc97d5a.png)
Here, the second layout(the one with small tabs with checkboxes) will look similar to this👇👇, with an added radio/checkbox for selection.
![Screenshot from 2020-05-13 21-04-24](https://user-images.githubusercontent.com/36303692/81835281-b471a580-955f-11ea-86ef-e4a2ddece430.png)

## Wireframe for creation of CFG file.
![wireframe_create_CFG_file](https://user-images.githubusercontent.com/36303692/81834905-3f05d500-955f-11ea-988c-1a3d2caa1648.png)
I have thought of designing the interactive editor(the one which is designed like HTML form) similar to VSCode's layout, having tabs, which can be switched over from time to time.
#### Please let me know, if the ideas are apt enough to convert them into UI.

**Comment by abhi211199** [comment]
@mfellows sir, I have been working on the UI mocks for the features related to file operations like creation of JSON, CFG files.
I have designed the basic layout of the dashboard, it will look better after materialised with ReactJS. 
![json](https://user-images.githubusercontent.com/36303692/82065678-0cd5ae00-96ec-11ea-804a-3662454620a1.png)
![cfg](https://user-images.githubusercontent.com/36303692/82065673-0ba48100-96ec-11ea-9885-7d131e23cc05.png)
![package](https://user-images.githubusercontent.com/36303692/82065664-0810fa00-96ec-11ea-89dd-1f3f0507b59b.png)
I would like to know your reviews and preferred color schemes for designing the UI.

**Comment by mfellows** [comment]
Looks great! One thing I overlooked before but we will definitely want to have is the ability to open an existing CFG or set of JSON files, similar to what was in your original prototype.

The situation would be where a user already has a simulation set up (for example, the Standalone_Template project) and wants to make some small changes using the new editor. They could browse to either Standalone_Template\gcbm_project and open gcbm_config.cfg, which points to a set of related JSON files, or they could open the whole set of files in Standalonte_Template\gcbm_project\templates (since there's no CFG file in there, it would just open all the JSON files contained in the directory).

**Comment by abhi211199** [comment]
@mfellows sir, we can provide the user with three options for opening existing files:
- open a single JSON file
- open multiple JSON files
- open files pointed by a CFG file(here user needs to select a CFG file and editor will automatically open all JSON files mentioned in the CFG file).

Once the editor fetches a JSON file(whatever be the mode it was chosen to open that file), the editor will map the JSON keys with our editor's keys and automatically populate the values corresponding to them.
I think, this will tackle all usecases regarding opening a file.
